# Generated by Django 5.1.6 on 2025-03-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0002_alter_airlineuser_options_alter_booking_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('flight', 'seat_number')},
        ),
    ]
