# Generated by Django 5.1.6 on 2025-03-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0003_remove_flight_available_seats_flight_total_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seat',
            field=models.IntegerField(default=0),
        ),
    ]
