# Generated by Django 5.1.6 on 2025-03-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0004_flight_available_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='available_seat',
            new_name='available_seats',
        ),
    ]
